# Generated by Django 4.2.2 on 2023-06-15 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_ID', models.CharField(max_length=20, unique=True)),
                ('product_name', models.CharField(max_length=30)),
                ('product_category', models.CharField(max_length=30)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_Id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pragma_challenge.product')),
            ],
        ),
    ]
